---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo-pod
  labels:
    app: demoApp
spec:
  containers:
    - name: docker-demo-app
      image: briandoc020500/docker-demo-app
      ports:
        - containerPort: 3000
